name: Deploy GitHub Pages com Validações

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Validação de HTML
        uses: Cyb3r-Jak3/html5validator-action@v0.2.0        
        with:
          root: .

      - name: Lint de CSS com Stylelint
        run: |
          npm install -g stylelint stylelint-config-standard
          echo 'module.exports = { extends: "stylelint-config-standard" }' > stylelint.config.js
          stylelint "**/*.css" || true

      - name: Verificação de integridade e tamanho do index.html
        run: |
          echo "Tamanho do index.html:"
          du -h index.html
          test $(wc -c < index.html) -lt 1000000

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload do conteúdo
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy no GitHub Pages
        uses: actions/deploy-pages@v4
