name: Validação e Preview Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  validate-and-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Validação de HTML
        uses: Cyb3r-Jak3/html5validator-action@v0.4.0
        with:
          root: .

      - name: Lint de CSS com Stylelint
        run: |
          npm install -g stylelint stylelint-config-standard
          echo 'module.exports = { extends: "stylelint-config-standard" }' > stylelint.config.js
          stylelint "**/*.css" || true

      - name: Verificação de tamanho do index.html
        run: |
          echo "Tamanho do index.html:"
          du -h index.html
          test $(wc -c < index.html) -lt 1000000

      - name: Empacotar preview
        run: |
          mkdir preview
          cp index.html preview/index.html

      - name: Fazer upload do preview como artefato
        uses: actions/upload-artifact@v4
        with:
          name: preview-haneybank
          path: preview/index.html
